config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'recipes/main_page'
  root 'recipes#main_page'

  resources :recipes, controller: "recipes"

  get "/users/:id" => "users#show", as: "user_page"

  get "/recipes/user/:id" => "recipes#user_recipe", as: "user_recipe"
  get "/recipes/favourite/user/:id" => "recipes#favourite", as: "favourite_recipe"
  post "/favourite/:id" => "recipes#favourite_new", as: "favourite_new"
  delete "/favourite/:id" => "recipes#favourite_destroy", as: "favourite_destroy"
  delete "/recipes/:id" => "recipes#destroy", as: "destroy_recipe"
  
  get "/recipes/:recipe_id/review" => "reviews#new", as: "new_review"
  post "/recipes/:recipe_id/review" => "reviews#create"
  get  "/recipes/:recipe_id/review/user/:user_id" => "reviews#edit", as: "edit_review"
  put "/recipes/:recipe_id/review/user/:user_id" => "reviews#update"
  patch "/recipes/:recipe_id/review/user/:user_id" => "reviews#update"
  delete "/recipes/:recipe_id/review/user/:user_id" => "reviews#destroy", as: "destroy_review"

  get "/search" => "searches#_search", as: "searching"
  get "/advance_search" => "searches#advance_search"
  post "/advance_searching" => "searches#advance_searching"

  get "/login" => "users#login"
  get "/logout" => "users#logout"
  get "/signup" => "users#signup"
  post "/login" => "users#login_check", as: "login_check"
  post "/signup" => "users#signup_create", as: "signup_create"

  get "/admin/user_management" => "admins#user_management", as: "user_management"
  delete "/users/:id" => "admins#user_delete", as: "user_delete"
end

app/views/navbar/_admin.html.erb
<%= link_to 'User Management', user_management_path, class: "nav-item nav-link active" %>
<div class="nav-item dropdown">
	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Your Page
    </a>
	<div class="dropdown-menu" role="menu" aria-labelledby="navbarDropdownMenuLink">
		<a class="dropdown-item" href="<%= user_page_path(current_user.id) %>">Your account</a>
        <a class="dropdown-item" href="<%= user_recipe_path(current_user.id) %>">Your recipes</a>
        <a class="dropdown-item" href="<%= favourite_recipe_path(current_user.id) %>">Your favourites</a>
	</div>
</div>
<%= link_to 'Log out', "/logout", class: "nav-item nav-link active" %>
<%= render partial: "searches/search" %>

app/views/navbar/_pre_login.html.erb
<%= link_to 'Log in', "/login", class: "nav-item nav-link active" %>
<%= link_to 'Sign up', "/signup", class: "nav-item nav-link active" %>

app/views/navbar/_regular.html.erb
<div class="nav-item dropdown">
	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Your Page
    </a>
	<div class="dropdown-menu" role="menu" aria-labelledby="navbarDropdownMenuLink">
		<a class="dropdown-item" href="<%= user_page_path(current_user.id) %>">Your account</a>
        <a class="dropdown-item" href="<%= user_recipe_path(current_user.id) %>">Your recipes</a>
        <a class="dropdown-item" href="<%= favourite_recipe_path(current_user.id) %>">Your favourites</a>
	</div>
</div>
<%= link_to 'Log out', "/logout", class: "nav-item nav-link active navbar-right " %>
<%= render partial: "searches/search" %>