config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'recipes/main_page'
  root 'recipes#main_page'

  resources :recipes, controller: "recipes"

  get "/users/:id" => "users#show", as: "user_page"

  get "/recipes/user/:id" => "recipes#user_recipe", as: "user_recipe"
  get "/recipes/favourite/user/:id" => "recipes#favourite", as: "favourite_recipe"
  post "/favourite/:id" => "recipes#favourite_new", as: "favourite_new"
  delete "/favourite/:id" => "recipes#favourite_destroy", as: "favourite_destroy"
  delete "/recipes/:id" => "recipes#destroy", as: "destroy_recipe"
  
  get "/recipes/:recipe_id/review" => "reviews#new", as: "new_review"
  post "/recipes/:recipe_id/review" => "reviews#create"
  get  "/recipes/:recipe_id/review/user/:user_id" => "reviews#edit", as: "edit_review"
  put "/recipes/:recipe_id/review/user/:user_id" => "reviews#update"
  patch "/recipes/:recipe_id/review/user/:user_id" => "reviews#update"
  delete "/recipes/:recipe_id/review/user/:user_id" => "reviews#destroy", as: "destroy_review"

  get "/search" => "searches#_search", as: "searching"
  get "/advance_search" => "searches#advance_search"
  post "/advance_searching" => "searches#advance_searching"

  get "/login" => "users#login"
  get "/logout" => "users#logout"
  get "/signup" => "users#signup"
  post "/login" => "users#login_check", as: "login_check"
  post "/signup" => "users#signup_create", as: "signup_create"

  get "/admin/user_management" => "admins#user_management", as: "user_management"
  delete "/users/:id" => "admins#user_delete", as: "user_delete"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :user
	has_many :favourites
	has_many :reviews

	scope :names, -> (name) { where("name ILIKE ?", "%#{name}%")}

	validates :name, presence: true
	validates :cooktime, presence: true
	validates :ingredients, presence: true
	validates :tags, presence: true

	def favourites_count
		favourites = Favourite.all.where(recipe_id: self.id)
		return favourites.count
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :recipes
	has_many :favourites
	has_many :reviews
	has_many :reports

	validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: true
	validates :password, presence: true, length: { minimum: 8 }

	before_create { generate_token(:auth_token) }

	mount_uploader :image_profile, AvatarUploader

	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end

	def recipes_count
		recipes = Recipe.all.where(user_id: self.id)
		return recipes.count
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe.ingredients = params[:recipe][:ingredients].split(",")
		@recipe.tags = params[:recipe][:tags].split(",")
		@recipe.user_id = current_user.id
		if @recipe.save
			redirect_to user_recipe_path(current_user.id)
		else
			redirect_to root_path
		end
	end

	def show
		@recipe = Recipe.find_by(id: params[:id])
		@review = Review.all.where(recipe_id: params[:id])

		if cookies[:auth_token]
			if Review.find_by(user_id: current_user.id, recipe_id: @recipe.id)
				@user_review = Review.find_by(user_id: current_user.id, recipe_id: @recipe.id)
			end
		end
	end

	def index
		@recipe = Recipe.all.order(:created_at).page params[:page]
	end

	def edit
		@recipe = Recipe.find_by(id: params[:id])
	end

	def update
		@recipe = Recipe.find_by(id: params[:id])
		@recipe.update(recipe_params)
		@recipe.ingredients = params[:recipe][:ingredients].split(",")
		@recipe.tags = params[:recipe][:tags].split(",")
		@recipe.save

		redirect_to "/recipes/#{params[:id]}"
	end

	def destroy
		@recipe = Recipe.find_by(id: params[:id])
		@recipe.destroy
		redirect_to user_recipe_path(current_user.id)
	end

	def user_recipe
		@user = User.find_by(id: params[:id])
		@recipe = Recipe.all.where(user_id: params[:id]).order(:created_at).page params[:page]
	end

	def favourite_new
		@favourite = Favourite.new(recipe_id: params[:id], user_id: current_user.id)
		@favourite.save

		redirect_to "/recipes/#{params[:id]}"
	end

	def favourite_destroy
		@favourite = Favourite.find_by(recipe_id: params[:id], user_id: current_user.id)
		@favourite.destroy

		redirect_to "/recipes/#{params[:id]}"
	end

	def favourite
		@user = User.find_by(id: params[:id])

		@recipe = []
		favourite = Favourite.all.where(user_id: params[:id])

		favourite.each do |f|
			@recipe << f.recipe
		end

	end

	def main_page
		@recipe_ids = Recipe.ids
	end

	private
	def recipe_params
		params.require(:recipe).permit(:name,:description,:cooktime,:tags,:ingredients,:instruction,:images)
	end
end

app/helpers/recipes_helper.rb
module RecipesHelper
	
end

app/views/recipes/_form.html.erb
<div class="text-field">
	<%= form.label :name %>
	<%= form.text_field :name %>
</div>
<br>

<div class="file-field">
	<%= form.label :images %>
	
	<%= form.file_field :images %>
</div>
<br>

<div class="text-field">
	<%= form.label :description %>
	<input id="recipe_description" type="hidden" value="<%= @recipe.description %>" name="recipe[description]">
  	<trix-editor input="recipe_description"></trix-editor>
</div>
<br>

<div class="text-field">
	<%= form.label :cooktime %>
	<%= form.text_field :cooktime %>
</div>
<br>

<div class="text-field">
	<%= form.label :ingredients %>
	<%= form.text_field :ingredients %>
	<p>Warning: Please seperate the ingredients with commas</p>
</div>
<br>

<div class="text-field">
	<%= form.label :instruction %>
	<input id="recipe_instruction" type="hidden" value="<%= @recipe.instruction %>" name="recipe[instruction]">
  <trix-editor input="recipe_instruction"></trix-editor>
</div>
<br>

<div class="text-field">
	<%= form.label :tags %>
	<%= form.text_field :tags %>
	<p>Warning: Please seperate the tags with commas</p>
</div>

<div class="submit-field">
	<%= form.submit %>
</div>

app/views/recipes/edit.html.erb
<div class="card width_90 title_card border-primary">
	<h1>Edit Your Recipe</h1>
</div>
<div class="card width_90 border-primary">
	<%= form_for @recipe, url: {controller: "recipes", action: "update", method: "put" } do |form| %>
		<%= render partial: '/recipes/form', object: form %>
	<% end %>
</div>

app/views/recipes/favourite.html.erb
<div class="card width_90 title_card border-primary">
	<h1><%= @user.username %> favourite recipes</h1>
</div>

<% @recipe.each do |r| %>
	<a href="/recipes/<%= r.id %>" class="custom-card">
		<div class="card card_box border-primary">
			<div class="row">
				<div class="col-md-8">
					<div class="card border-white">
						<div class="card-body">
							<h2 class="card-title"><%= r.name %></h2>
							<p class="card-text">Created by: <%= r.user.username %></p>
							<p class="card-text">Overall rating: <%= Review.overall_rating(r.id) %> / 5</p>
							<p class="card-text"><%= sanitize r.description %></p>
							<p class="card-text">Last edited: <%= r.created_at.strftime("%Y-%m-%d") %></p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card">
						<img class="img-thumbnail pull-right" src="<%= r.images %>">
					</div>
				</div>
			</div>
		</div>
	</a>
<% end %>

app/views/recipes/index.html.erb
<div class="card width_90 title_card border-primary">
	<h1>All the latest recipes posted</h1>
</div>

<% @recipe.each do |r| %>
	<a href="/recipes/<%= r.id %>" class="custom-card">
		<div class="card card_box border-primary">
			<div class="row">
				<div class="col-md-8">
						<div class="card border-white">
							<div class="card-body">
								<h2 class="card-title"><%= r.name %></h2>
								<p class="card-text">Created by: <%= r.user.username %></p>
								<p class="card-text">Overall rating: <%= Review.overall_rating(r.id) %> / 5</p>
								<p class="card-text"><%= sanitize r.description %></p>
								<p class="card-text">Last edited: <%= r.created_at.strftime("%Y-%m-%d") %></p>
							</div>
						</div>
				</div>
				<div class="col-md-4">
					<div class="card">
						<img class="img-thumbnail pull-right" src="<%= r.images %>">
					</div>
				</div>
			</div>
		</div>
	</a>
<% end %>

<div class="pages text-center">
	<%= paginate @recipe %>
	<%= page_entries_info @recipe %>
</div>

app/views/recipes/main_page.html.erb
<div class="card-deck">
  <% 8.times do %>
    <% @r = Recipe.find_by(id: @recipe_ids[rand(@recipe_ids.length - 1)])  %>
    <% unless @r == nil %>
      <div class="col-md-3 mt-3">
        <a href="/recipes/<%= @r.id %>" class="custom-card">
          <div class="card">
            <img class="card-img-top" src="<%= @r.images %>" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"><%= @r.name %></h5>
            </div>
            <div class="card-footer">
              <% (Review.overall_rating(@r.id)).to_i.times do %>
                <span class="fa fa-star checked"></span>
              <% end %>
              <% (5 - Review.overall_rating(@r.id)).to_i.times do %>
                <span class="fa fa-star"></span>
              <% end %>
            </div>
          </div>
        </a>
      </div>
      <% @recipe_ids.delete(@r.id) %>
    <% end %>
  <% end %>
</div>

<div class="pages text-center">
  <b>There are <%= Recipe.all.count %> recipes and <%= User.all.count %> users.</b>
</div>

app/views/recipes/new.html.erb
<div class="card width_90 title_card border-primary">
	<h1>Add Your Recipe</h1>
</div>
<div class="card width_90 border-primary">
	<%= form_for @recipe, url: {controller: "recipes", action: "create", method: "post" } do |form| %>
		<%= render partial: '/recipes/form', object: form %>
	<% end %>
</div>

app/views/recipes/show.html.erb
<div class="card width_90 border-primary">
	<h1><%= @recipe.name %></h1>
	<% if cookies[:auth_token] %>
		<% if current_user.id == @recipe.user_id %>
			<%= link_to 'Edit', edit_recipe_path(@recipe.id) %>
			<%= link_to 'Delete', destroy_recipe_path(@recipe.id), method: :delete, data: {confirm: "Are you sure?" } %>
		<% else %>
			<% if Favourite.find_by(recipe_id: @recipe.id, user_id: current_user.id) %>
				<%= link_to 'Unfollow', favourite_destroy_path(@recipe.id), method: :delete, data: {confirm: "Are you sure?" } %>
			<% else %>
				<%= link_to 'Follow', favourite_new_path(@recipe.id), method: "post" %>
			<% end %>
		<% end %>
	<% end %>

	<p>Overall rating: <%= Review.overall_rating(@recipe.id) %> / 5</p>
	<p>Favourites: <%= @recipe.favourites_count %></p>
	<p>Estimated cook time: <%= @recipe.cooktime %></p>
	<% if @recipe.images %>
		<img class="card-img-top" src="<%= @recipe.images %>"  alt="Card image cap"%>
	<% end %>
	<p><%= sanitize @recipe.description %></p>

	<h3>Ingredients:</h3>
	<ol>
		<% @recipe.ingredients.each do |ingredient| %>
			<li><%= ingredient %></li>
		<% end %>
	</ol>

	<h3>Instruction:</h3>
	<p><%= sanitize @recipe.instruction %></p>

	<h3>Food type</h3>
	<p>
		<% @recipe.tags.each do |tag| %>
			<%= tag %> | 
		<% end %>
	</p>
</div>

<% if @user_review %>
	<div class="card width_90">
		<h4>Your Review</h4>
		<%= link_to 'Edit your Review', edit_review_path(@recipe.id,current_user.id), class: "card-link" %>
		<%= link_to 'Delete', destroy_review_path(@recipe.id,current_user.id), class: "card-link" , method: :delete, data: {confirm: "Are you sure?" } %>
		<p><%= @user_review.title %></p>
		<p>Rating: <%= @user_review.rating %></p>
		<p><%= sanitize @user_review.description %></p>
	</div>
<% end %>

<div class="card width_90">
	<h3>Reviews</h3>
	<% if cookies[:auth_token] %>
		<% unless @user_review %>
			<%= link_to 'Write a Review', new_review_path(@recipe.id) %>
		<% end %>
	<% end %>
	<% line_break = 1 %>
	<% @review.each do |r| %>
		<h4><%= r.title %></h4>
		<p>By: <%= r.user.username %></p>
		<p>Rating: <%= r.rating %></p>
		<p><%= sanitize r.description %></p>
		<% unless line_break == @review.count %>
			<% line_break += 1 %>
			<hr>
		<% end %>
	<% end %>
</div>

app/views/recipes/user_recipe.html.erb
<div class="card width_90 title_card border-primary">
	<h1><%= @user.username %> recipes</h1>
</div>

<% if current_user.id == @user.id %>
	<div class="card width_90 title_card border-primary">
		<%= link_to 'Create a new recipe', new_recipe_path %>
	</div>
<% end %>

<% @recipe.each do |r| %>
	<a href="/recipes/<%= r.id %>" class="custom-card">
		<div class="card card_box border-primary">
			<div class="row">
				<div class="col-md-8">
					<div class="card border-white">
						<div class="card-body">
							<h2 class="card-title"><%= r.name %></h2>
							<p class="card-text">Created by: <%= r.user.username %></p>
							<p class="card-text">Overall rating: <%= Review.overall_rating(r.id) %> / 5</p>
							<p class="card-text"><%= sanitize r.description %></p>
							<p class="card-text">Last edited: <%= r.created_at.strftime("%Y-%m-%d") %></p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card">
						<img class="img-thumbnail pull-right" src="<%= r.images %>">
					</div>
				</div>
			</div>
		</div>
	</a>
<% end %>

<div class="pages text-center">
	<%= paginate @recipe %>
	<%= page_entries_info @recipe %>
</div>