config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'recipes/main_page'
  root 'recipes#main_page'

  resources :recipes, controller: "recipes"

  get "/users/:id" => "users#show", as: "user_page"

  get "/recipes/user/:id" => "recipes#user_recipe", as: "user_recipe"
  get "/recipes/favourite/user/:id" => "recipes#favourite", as: "favourite_recipe"
  post "/favourite/:id" => "recipes#favourite_new", as: "favourite_new"
  delete "/favourite/:id" => "recipes#favourite_destroy", as: "favourite_destroy"
  delete "/recipes/:id" => "recipes#destroy", as: "destroy_recipe"
  
  get "/recipes/:recipe_id/review" => "reviews#new", as: "new_review"
  post "/recipes/:recipe_id/review" => "reviews#create"
  get  "/recipes/:recipe_id/review/user/:user_id" => "reviews#edit", as: "edit_review"
  put "/recipes/:recipe_id/review/user/:user_id" => "reviews#update"
  patch "/recipes/:recipe_id/review/user/:user_id" => "reviews#update"
  delete "/recipes/:recipe_id/review/user/:user_id" => "reviews#destroy", as: "destroy_review"

  get "/search" => "searches#_search", as: "searching"
  get "/advance_search" => "searches#advance_search"
  post "/advance_searching" => "searches#advance_searching"

  get "/login" => "users#login"
  get "/logout" => "users#logout"
  get "/signup" => "users#signup"
  post "/login" => "users#login_check", as: "login_check"
  post "/signup" => "users#signup_create", as: "signup_create"

  get "/admin/user_management" => "admins#user_management", as: "user_management"
  delete "/users/:id" => "admins#user_delete", as: "user_delete"
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :recipes
	has_many :favourites
	has_many :reviews
	has_many :reports

	validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: true
	validates :password, presence: true, length: { minimum: 8 }

	before_create { generate_token(:auth_token) }

	mount_uploader :image_profile, AvatarUploader

	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end

	def recipes_count
		recipes = Recipe.all.where(user_id: self.id)
		return recipes.count
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find_by(id: params[:id])
		@recipe_ids = Recipe.all.where(user_id: params[:id]).ids
		@favourite_ids = Favourite.all.where(user_id: params[:id]).ids
	end

	def signup
		@user = User.new
	end

	def signup_create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_path
		else
			redirect_to "/signup"
		end
	end

	def login
		@user = User.new
	end

	def login_check
		@user = User.find_by(email: params[:user][:email])
		if @user && @user.authenticate(params[:user][:password])
			if params[:remember_me]
				cookies.permanent[:auth_token] = @user.auth_token
			else
				cookies[:auth_token] = @user.auth_token
			end
			redirect_to root_path
		else
			redirect_to "/login"
		end
	end

	def logout
		cookies.delete(:auth_token)
		@user = nil
		redirect_to root_path
	end

	private
	def user_params
	  params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user
		if cookies[:auth_token]
			@current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def sign_in(user)
		cookies[:auth_token] = user.auth_token
	end

	def sign_out
		cookies[:auth_token] = nil
	end

	def user_avatar user
	  if user.image_profile.present?
	    image_tag user.image_profile, class: "rounded float-right"
	  else
	    # Assuming you have a default.jpg in your assets folder
	    image_tag 'empty_profile.jpeg', class: "rounded float-right",  height: "200", width: "200"
	  end
	end
end

app/views/users/_form.html.erb
  <div class="form-group">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <%= form.submit 'Create User', class: "btn btn-primary" %>

app/views/users/login.html.erb
<div class="card width_90 title_card border-primary">
  <h2>Log into your account</h2>
</div>

<div class="card width_90 title_card border-primary">
  <%= form_for @user, url: login_check_path do |form| %>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, type: 'email',  class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password,  class: "form-control"  %>
    </div>

    <div class="form-group form-check">
      <%= check_box_tag :remember_me, 1, params[:remember_me] %>
      <%= form.label :remember_me %>
    </div>

    <%= form.submit 'Sign in', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="card width_90">
	<!-- User Info -->
	<% if current_user.id == @user.id %>
		<h1>Welcome, <%= @user.username %>!</h1>
	<% else %>
		<h1>Welcome to <%= @user.username %> page</h1>
	<% end %>
	<%= user_avatar @user %>
</div>

<br>

	<!-- User Recipe -->
<div class="card width_90">
	<a href="<%= user_recipe_path(params[:id]) %>"><h1>Recipes (<%= @recipe_ids.count %>)</h1></a>
	<% if @recipe_ids.count == 0 %>
		<div class="card card_box border-primary">
			<p class="text-muted">This user has no recipes.</p>
		</div>
	<% else %>
		<% 3.times do %>
			<% if @recipe_ids.count > 0 %>
				<% r = Recipe.find_by(id: @recipe_ids[0]) %>
				<hr>
				<div class="card card_box border-white">
					<div class="row">
						<div class="col-md-8">
								<div class="card border-white">
									<div class="card-body">
										<a href="/recipes/<%= r.id %>"><h2 class="card-title"><%= r.name %></h2></a>
										<p class="card-text">Overall rating: <%= Review.overall_rating(r.id) %> / 5</p>
										<p class="card-text"><%= sanitize r.description %></p>
									</div>
								</div>
						</div>
						<div class="col-md-4">
							<div class="card">
								<img class="img-thumbnail pull-right" src="<%= r.images %>">
							</div>
						</div>
					</div>
				</div>
				<% @recipe_ids.shift %>
			<% end %>
		<% end %>
	<% end %>
</div>
<br>

	<!-- User Favourites -->
<div class="card width_90">
	<a href="<%= favourite_recipe_path(params[:id]) %>"><h1>Favourites (<%= @favourite_ids.count %>)</h1></a>
	<% if @favourite_ids.count == 0 %>
		<div class="card card_box border-primary">
			<p class="text-muted">This user has no favourite recipes.</p>
		</div>
	<% else %>
		<% 3.times do %>
			<% if @favourite_ids.count > 0 %>
				<% f = Favourite.find_by(id: @favourite_ids[0]).recipe %>
				<hr>
				<div class="card card_box border-white">
					<div class="row">
						<div class="col-md-8">
								<div class="card border-white">
									<div class="card-body">
										<a href="/recipes/<%= f.id %>"><h2 class="card-title"><%= f.name %> (<%= f.user.username %>) </h2></a>
										<p class="card-text">Overall rating: <%= Review.overall_rating(f.id) %> / 5</p>
										<p class="card-text"><%= sanitize f.description %></p>
									</div>
								</div>
						</div>
						<div class="col-md-4">
							<div class="card">
								<img class="img-thumbnail pull-right" src="<%= f.images %>">
							</div>
						</div>
					</div>
				</div>
				<% @favourite_ids.shift %>
			<% end %>
		<% end %>
	<% end %>
</div>

app/views/users/signup.html.erb
<div class="card width_90 title_card border-primary">
	<h2>Sign up for an account!</h2>
</div>

<div class="card width_90 border-primary">
	<%= form_for @user, url: signup_create_path do |form| %>
		<%= render partial: "users/form", object: form %>
	<% end %>
</div>