config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'recipes/main_page'
  root 'recipes#main_page'

  resources :recipes, controller: "recipes"

  get "/users/:id" => "users#show", as: "user_page"

  get "/recipes/user/:id" => "recipes#user_recipe", as: "user_recipe"
  get "/recipes/favourite/user/:id" => "recipes#favourite", as: "favourite_recipe"
  post "/favourite/:id" => "recipes#favourite_new", as: "favourite_new"
  delete "/favourite/:id" => "recipes#favourite_destroy", as: "favourite_destroy"
  delete "/recipes/:id" => "recipes#destroy", as: "destroy_recipe"
  
  get "/recipes/:recipe_id/review" => "reviews#new", as: "new_review"
  post "/recipes/:recipe_id/review" => "reviews#create"
  get  "/recipes/:recipe_id/review/user/:user_id" => "reviews#edit", as: "edit_review"
  put "/recipes/:recipe_id/review/user/:user_id" => "reviews#update"
  patch "/recipes/:recipe_id/review/user/:user_id" => "reviews#update"
  delete "/recipes/:recipe_id/review/user/:user_id" => "reviews#destroy", as: "destroy_review"

  get "/search" => "searches#_search", as: "searching"
  get "/advance_search" => "searches#advance_search"
  post "/advance_searching" => "searches#advance_searching"

  get "/login" => "users#login"
  get "/logout" => "users#logout"
  get "/signup" => "users#signup"
  post "/login" => "users#login_check", as: "login_check"
  post "/signup" => "users#signup_create", as: "signup_create"

  get "/admin/user_management" => "admins#user_management", as: "user_management"
  delete "/users/:id" => "admins#user_delete", as: "user_delete"
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	def _search
		@recipe = Recipe.all.order(:created_at).page params[:page]
		
		@recipe = @recipe.names(params[:name]) if params[:name].present?

		render "index"
	end

	def index
		
	end

	def advance_search

	end

	def advance_searching
		@name = params[:name]
		@recipe = Recipe.all
		
		@recipe = @recipe.names(params[:name]) if params[:name].present?
	    respond_to do |format|
	      # format.json { render json: @recipe.map {|r| [r, r.user.username] } }
	      format.js # remote: true is sent a js format and sends you to search.js.erb
	    end
	end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<%= form_for "", url: searching_path, method: :get do |form| %>
	<%= form.text_field :name, id: "name", placeholder: "Search" %>
	
	<%= form.submit 'Search' %>
<% end %>

app/views/searches/advance_search.html.erb
<div id="home">
  <div class="card width_90 title_card border-primary">
    <h2>Advance Searching</h2>

    <div id="search-div">
      <%= form_tag advance_searching_path, id: "recipe-search", remote: true do %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= label_tag "search" %>
        <%= text_field_tag "name", nil, list: "list", placeholder: 'Enter search term...' %>
        <!-- <select id="list" onchange="if (this.value) window.location.href=this.value">
        	<option>Select Here...</option>
        </select> -->
      <% end %>
    </div>
  </div>

  <div id="search-result">
    
  </div>
</div>

app/views/searches/advance_searching.js.erb
$("#list").html("");
$("#search-result").html("");
var first_option = document.createElement("option");
first_option.innerHTML = "Select Here...";
$("#list").append(first_option);

<% @recipe.each do |r| %>
  var option = document.createElement("option");
  option.value = '/recipes/<%= r.id %>';
  option.innerHTML = "<%= r.name %> (<%= r.user.username %>)";

  //append option to list
  $("#list").append(option);

  //Add the search result in "search-result" id
  var a = document.createElement("a")

  var card = document.createElement("div");
  
  var title = document.createElement("h2");
  title.innerHTML = "<%= r.name %> (<%= r.user.username %>)";

  var p = document.createElement("p");
  p.innerHTML = "<%= sanitize r.description %>";

  card.append(title);
  card.append(p);
  a.append(card);
  $("#search-result").append(a);
  $( "div:last" ).addClass( "card card_box border-primary" );
  $( "h2:last" ).addClass( "card-title" );
  $( "p:last" ).addClass( "card-text" );
  $( "a:last" ).attr("href", "/recipes/<%= r.id %>").addClass( "custom-card" );
<% end %>

app/views/searches/index.html.erb
<div class="card width_90 title_card border-primary">
	<h1>Your search result</h1>
</div>

<% @recipe.each do |r| %>
	<a href="/recipes/<%= r.id %>" class="custom-card">
		<div class="card card_box border-primary">
			<div class="row">
				<div class="col-md-8">
						<div class="card border-white">
							<div class="card-body">
								<h2 class="card-title"><%= r.name %></h2>
								<p class="card-text">Created by: <%= r.user.username %></p>
								<p class="card-text">Overall rating: <%= Review.overall_rating(r.id) %> / 5</p>
								<p class="card-text"><%= sanitize r.description %></p>
								<p class="card-text">Last edited: <%= r.created_at.strftime("%Y-%m-%d") %></p>
							</div>
						</div>
				</div>
				<div class="col-md-4">
					<div class="card">
						<img class="img-thumbnail pull-right" src="<%= r.images %>">
					</div>
				</div>
			</div>
		</div>
	</a>
<% end %>

<div class="pages text-center">
	<%= paginate @recipe %>
	<%= page_entries_info @recipe %>
</div>